from typing import NoReturn

from fastapi import HTTPException


AUTH_MISSING_USER = "AUTH_MISSING_USER"
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"

INPUT_VALIDATION_FAILED = "INPUT_VALIDATION_FAILED"

FILE_NAME_REQUIRED = "FILE_NAME_REQUIRED"
FILE_TYPE_PDF_ONLY = "FILE_TYPE_PDF_ONLY"
PDF_NO_TEXT = "PDF_NO_TEXT"
PDF_GARBLED_TEXT = "PDF_GARBLED_TEXT"
PDF_AI_REJECTED = "PDF_AI_REJECTED"
FILE_PROCESSING_FAILED = "FILE_PROCESSING_FAILED"

MATERIALS_NO_RELEVANT = "MATERIALS_NO_RELEVANT"

AI_PROVIDER_UNSUPPORTED = "AI_PROVIDER_UNSUPPORTED"
AI_API_KEY_MISSING = "AI_API_KEY_MISSING"
AI_AUTH_FAILED = "AI_AUTH_FAILED"
AI_RATE_LIMITED = "AI_RATE_LIMITED"
AI_TIMEOUT = "AI_TIMEOUT"
AI_BAD_GATEWAY = "AI_BAD_GATEWAY"
AI_EMPTY_RESPONSE = "AI_EMPTY_RESPONSE"
AI_RESPONSE_PARSE_FAILED = "AI_RESPONSE_PARSE_FAILED"

SPEAKING_NO_AUDIO = "SPEAKING_NO_AUDIO"
SPEAKING_GROQ_KEY_MISSING = "SPEAKING_GROQ_KEY_MISSING"
SPEAKING_TRANSCRIBE_FAILED = "SPEAKING_TRANSCRIBE_FAILED"
SPEAKING_TRANSCRIBE_PROVIDER_ERROR = "SPEAKING_TRANSCRIBE_PROVIDER_ERROR"
SPEAKING_FEEDBACK_PARSE_FAILED = "SPEAKING_FEEDBACK_PARSE_FAILED"
SPEAKING_FEEDBACK_FAILED = "SPEAKING_FEEDBACK_FAILED"

TASK_INVALID_LEVEL = "TASK_INVALID_LEVEL"
TASK_VALIDATION_FAILED = "TASK_VALIDATION_FAILED"
TASK_GENERATION_FAILED = "TASK_GENERATION_FAILED"

PLACEMENT_GENERATION_FAILED = "PLACEMENT_GENERATION_FAILED"
PLACEMENT_EVALUATION_FAILED = "PLACEMENT_EVALUATION_FAILED"

USER_SERVICE_UNREACHABLE = "USER_SERVICE_UNREACHABLE"
USER_SERVICE_UNAUTHORIZED = "USER_SERVICE_UNAUTHORIZED"
USER_SERVICE_BAD_RESPONSE = "USER_SERVICE_BAD_RESPONSE"
USER_SERVICE_BAD_REQUEST = "USER_SERVICE_BAD_REQUEST"
USER_TOKENS_EMPTY = "USER_TOKENS_EMPTY"


def raise_with_code(
    code: str, status_code: int, message: str
) -> NoReturn:
    raise HTTPException(
        status_code=status_code,
        detail={"code": code, "message": message},
    )
