name: diploma-thesis

version: '3.8'

services:

  postgres-auth:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: authdb
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  postgres-user:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: userdb
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'  # AMQP protocol port
      - '15672:15672'  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_auth_data:
  postgres_user_data:
  rabbitmq_data:
