version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  auth-microservice:
    build:
      context: ./Backend/authMicroservice
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${redis-host}
      REDIS_PORT: ${redis-port}
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start"

  gateway:
    build:
      context: ./Backend/Gateway
    ports:
      - '3001:3001' 
    depends_on:
      - auth-microservice
      - redis
    environment:
      AUTH_MICROSERVICE_URL: ${AUTH_MICROSERVICE_URL}
      GATEWAY_PORT: 3001
    command: >
      sh -c "npm run start"

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - auth-microservice

volumes:
  postgres_data:
  redis_data:
