import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

PRICES = {
    "GPT-5.2": 10.0,
    "Gemini 3 Flash": 0.1,
    "Llama 4": 0.2,
    "Mistral Large 3": 2.0,
    "Qwen 3 Max": 1.0
}

def estimate_tokens(text):
    if pd.isna(text): return 0
    return len(str(text)) / 4 

def generate_assets():
    csv_path = "archive/results/benchmark_2025_scientific_results.csv"
    if not os.path.exists(csv_path):
        print("CSV not found!")
        return

    df = pd.read_csv(csv_path)
    df['score'] = pd.to_numeric(df['score'], errors='coerce').fillna(0)
    
    # Оценка токенов и стоимости
    df['estimated_tokens'] = df['content'].apply(estimate_tokens) + 200 # + prompt tokens
    df['cost_usd'] = df.apply(lambda row: (row['estimated_tokens'] / 1_000_000) * PRICES.get(row['model'], 0.5), axis=1)

    # 1. ГЕНЕРАЦИЯ ТАБЛИЦ ДЛЯ LATEX
    
    # Таблица 1: Leaderboard
    leaderboard = df.groupby('model').agg({
        'score': ['mean', 'std'],
        'latency': 'mean',
        'cost_usd': 'sum'
    }).reset_index()
    leaderboard.columns = ['Model', 'Mean Score', 'Stability (SD)', 'Avg Latency (s)', 'Total Est. Cost ($)']
    leaderboard = leaderboard.sort_values(by='Mean Score', ascending=False)
    
    with open('table_leaderboard.tex', 'w') as f:
        f.write("% LaTeX table generated by pandas\n")
        f.write(leaderboard.to_latex(index=False, 
                                   column_format='lcccc', 
                                   float_format="%.2f"))

    # Таблица 2: Сравнение по языкам и уровням
    lang_pivot = df.pivot_table(index=['lang', 'level'], columns='model', values='score', aggfunc='mean').reset_index()
    with open('table_lang_comparison.tex', 'w') as f:
        f.write("% LaTeX table generated by pandas\n")
        f.write(lang_pivot.to_latex(index=False, 
                                  float_format="%.2f"))

    # 2. ВЕКТОРНЫЕ ГРАФИКИ (PDF)
    sns.set_theme(style="whitegrid")
    
    # График 1: Efficiency (Score vs Cost)
    plt.figure(figsize=(8, 6))
    eff_df = df.groupby('model').agg({'score': 'mean', 'cost_usd': 'mean'}).reset_index()
    # Логарифмическая шкала для цены, т.к. разброс огромный
    eff_df['log_cost'] = np.log10(eff_df['cost_usd'] + 1e-7) 
    
    scatter = sns.scatterplot(data=eff_df, x='log_cost', y='score', hue='model', s=200)
    for i in range(eff_df.shape[0]):
        plt.text(eff_df.log_cost[i]+0.05, eff_df.score[i], eff_df.model[i], fontsize=9)
    
    plt.title('Cost-Efficiency Analysis (Log Scale Cost)')
    plt.xlabel('Log10(Estimated Cost per Request in USD)')
    plt.ylabel('Mean Quality Score (1-10)')
    plt.tight_layout()
    plt.savefig('plot_efficiency.pdf')
    
    # График 2: Stability (Boxplot)
    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df, x='score', y='model', palette='vlag')
    plt.title('Model Response Stability Comparison')
    plt.xlabel('Score')
    plt.ylabel('Model')
    plt.tight_layout()
    plt.savefig('plot_stability.pdf')

    print("All assets for LaTeX generated: 2 .tex files and 2 .pdf graphs.")

if __name__ == "__main__":
    generate_assets()

