process.env.KEY_ENCRYPTION_KEY =
  process.env.KEY_ENCRYPTION_KEY ??
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

process.env.INTERNAL_SERVICE_KEY =
  process.env.INTERNAL_SERVICE_KEY ?? "test-internal-key";
