/**
 * Translations for every lesson in Bridge's CURRICULUM (138 entries).
 *
 * Lives outside i18n.ts because dropping ~600 lines into the main
 * translation file made it unreadable. The lookup helper in
 * `src/utils/localizeContent.ts` reaches into these tables and falls
 * back to the raw English from the backend if a key is missing.
 *
 * Keys are camelCase slugs of the English title — see
 * `slugifyKey()` in localizeContent.ts. When backend curriculum
 * changes, run the dev script to regenerate keys.
 */
export interface LessonText {
  title: string;
  description: string;
}

export const LESSONS_EN: Record<string, LessonText> = {
  sayingHelloGoodbye: { title: "Saying Hello & Goodbye", description: "Learn the most essential daily greetings." },
  introducingYourself: { title: "Introducing Yourself", description: "State your name, age and where you come from." },
  countriesNationalities: { title: "Countries & Nationalities", description: "Name countries and corresponding nationality adjectives." },
  numbers1100: { title: "Numbers 1–100", description: "Count and use numbers in everyday contexts." },
  theVerbToBe: { title: "The Verb 'To Be'", description: "Master the most fundamental verb: am / is / are." },
  basicQuestionsAnswers: { title: "Basic Questions & Answers", description: "Ask and answer who, what, where questions." },
  familyMembers: { title: "Family Members", description: "Describe your family tree and relationships." },
  describingPeople: { title: "Describing People", description: "Talk about physical appearance and personality." },
  possessiveAdjectives: { title: "Possessive Adjectives", description: "Use my / your / his / her / our / their correctly." },
  haveGotTalkingAboutFamily: { title: "Have Got – Talking About Family", description: "Use 'have got' to describe what you own or who you know." },
  writingAboutYourFamily: { title: "Writing About Your Family", description: "Write a short paragraph introducing your family." },
  familyInterview: { title: "Family Interview", description: "Ask and answer questions about family life." },
  classroomObjects: { title: "Classroom Objects", description: "Name items found in learning environments." },
  colorsShapes: { title: "Colors & Shapes", description: "Describe your surroundings with colors and shapes." },
  articlesAAnThe: { title: "Articles: a / an / the", description: "Know when to use definite and indefinite articles." },
  thisThatTheseThose: { title: "This / That / These / Those", description: "Point to nearby and distant objects." },
  inTheClassroom: { title: "In the Classroom", description: "Describe objects around you using full sentences." },
  spellingTheAlphabet: { title: "Spelling & the Alphabet", description: "Spell words aloud using the English alphabet." },
  daysMonthsSeasons: { title: "Days, Months & Seasons", description: "Talk about the calendar: days, months and seasons." },
  tellingTheTime: { title: "Telling the Time", description: "Read and say what time it is." },
  dailyRoutineVerbs: { title: "Daily Routine Verbs", description: "Describe what you do from morning to night." },
  presentSimpleDailyHabits: { title: "Present Simple – Daily Habits", description: "Use present simple to talk about habitual actions." },
  frequencyAdverbs: { title: "Frequency Adverbs", description: "Express how often things happen." },
  myTypicalDay: { title: "My Typical Day", description: "Write or speak about your daily routine." },
  foodDrinkVocabulary: { title: "Food & Drink Vocabulary", description: "Name common foods and beverages." },
  orderingInARestaurant: { title: "Ordering in a Restaurant", description: "Have a real conversation in a café or restaurant." },
  countableVsUncountable: { title: "Countable vs Uncountable", description: "Use 'some', 'any', 'much', 'many' correctly." },
  expressingPreferences: { title: "Expressing Preferences", description: "Say what you like, dislike and prefer." },
  shoppingForFood: { title: "Shopping for Food", description: "Buy food in a market or supermarket." },
  recipesInstructions: { title: "Recipes & Instructions", description: "Understand cooking vocabulary and follow a recipe." },
  meansOfTransport: { title: "Means of Transport", description: "Name different vehicles and modes of transport." },
  buyingTickets: { title: "Buying Tickets", description: "Book and buy transport tickets." },
  askingForDirections: { title: "Asking for Directions", description: "Find your way in a new city." },
  pastSimpleRegularVerbs: { title: "Past Simple – Regular Verbs", description: "Talk about completed actions in the past." },
  pastSimpleIrregularVerbs: { title: "Past Simple – Irregular Verbs", description: "Master the most common irregular past tense forms." },
  describingAHoliday: { title: "Describing a Holiday", description: "Write or tell a story about a past trip." },
  roomsFurniture: { title: "Rooms & Furniture", description: "Describe the layout and contents of a home." },
  thereIsThereAre: { title: "There Is / There Are", description: "Describe what exists in a place." },
  prepositionsOfPlace: { title: "Prepositions of Place", description: "Describe where things are located." },
  describingYourHome: { title: "Describing Your Home", description: "Describe your house or flat in detail." },
  rentingAFlat: { title: "Renting a Flat", description: "Understand language for finding and renting property." },
  makingComparisons: { title: "Making Comparisons", description: "Compare places, objects, and people." },
  partsOfTheBody: { title: "Parts of the Body", description: "Name and locate parts of the human body." },
  commonIllnessesSymptoms: { title: "Common Illnesses & Symptoms", description: "Describe health problems and symptoms." },
  atTheDoctorS: { title: "At the Doctor's", description: "Communicate with a medical professional." },
  shouldShouldnT: { title: "Should / Shouldn't", description: "Give health advice using modal verbs." },
  healthyLifestyle: { title: "Healthy Lifestyle", description: "Write about habits for a healthy life." },
  goingToThePharmacy: { title: "Going to the Pharmacy", description: "Buy medicine and understand pharmacy instructions." },
  jobsResponsibilities: { title: "Jobs & Responsibilities", description: "Discuss types of work and professional duties." },
  presentPerfectTense: { title: "Present Perfect Tense", description: "Link past experiences to the present moment." },
  cvCoverLetter: { title: "CV & Cover Letter", description: "Write professional application documents." },
  jobInterviewLanguage: { title: "Job Interview Language", description: "Speak confidently in a formal job interview." },
  workplaceVocabulary: { title: "Workplace Vocabulary", description: "Navigate office life and business environments." },
  expressingFuturePlans: { title: "Expressing Future Plans", description: "Talk about intentions and plans for the future." },
  digitalLifeVocabulary: { title: "Digital Life Vocabulary", description: "Talk about technology, apps, and the internet." },
  thePassiveVoice: { title: "The Passive Voice", description: "Shift focus from actor to action using passive constructions." },
  discussingTechnology: { title: "Discussing Technology", description: "Share opinions about technology's role in society." },
  readingOnlineArticles: { title: "Reading Online Articles", description: "Understand complex digital content and media." },
  socialMediaCommunication: { title: "Social Media & Communication", description: "Write posts, comments and messages appropriately." },
  technologyProblems: { title: "Technology Problems", description: "Describe and troubleshoot tech issues." },
  natureLandscape: { title: "Nature & Landscape", description: "Describe natural environments and geographical features." },
  environmentalProblems: { title: "Environmental Problems", description: "Discuss climate change and ecological issues." },
  modalVerbsForObligation: { title: "Modal Verbs for Obligation", description: "Express duty, permission and prohibition." },
  solutionsActions: { title: "Solutions & Actions", description: "Propose and debate environmental solutions." },
  writingAReport: { title: "Writing a Report", description: "Structure a clear written report on an issue." },
  recyclingSustainability: { title: "Recycling & Sustainability", description: "Understand language around sustainable living." },
  hobbiesInterests: { title: "Hobbies & Interests", description: "Talk about free-time activities and pastimes." },
  gerundsInfinitives: { title: "Gerunds & Infinitives", description: "Use -ing forms and 'to + verb' in the right contexts." },
  talkingAboutFilmsBooks: { title: "Talking About Films & Books", description: "Summarize plots and express opinions on culture." },
  makingPlans: { title: "Making Plans", description: "Arrange events using future forms." },
  musicArt: { title: "Music & Art", description: "Discuss artistic works, genres and performances." },
  reviewWriting: { title: "Review Writing", description: "Write an engaging review of a film, book or place." },
  socialIssuesVocabulary: { title: "Social Issues Vocabulary", description: "Discuss complex topics affecting modern society." },
  conditionalSentencesAllTypes: { title: "Conditional Sentences (All Types)", description: "Master all conditionals for real and hypothetical events." },
  debatingArgumentation: { title: "Debating & Argumentation", description: "Express, develop and defend complex opinions." },
  opinionEssay: { title: "Opinion Essay", description: "Write a well-structured, persuasive opinion essay." },
  understandingStatistics: { title: "Understanding Statistics", description: "Read and discuss graphs, data and trends." },
  discourseConnectors: { title: "Discourse Connectors", description: "Improve flow using sophisticated linking expressions." },
  scientificVocabulary: { title: "Scientific Vocabulary", description: "Understand language used in science and research." },
  futureTensesAdvanced: { title: "Future Tenses – Advanced", description: "Express future probability, plans and predictions." },
  passiveVoiceAdvanced: { title: "Passive Voice – Advanced", description: "Use complex passive structures in academic writing." },
  scienceReport: { title: "Science Report", description: "Write a formal scientific report with findings." },
  discussingAiTheFuture: { title: "Discussing AI & The Future", description: "Debate the impact of technology and artificial intelligence." },
  causeEffectLanguage: { title: "Cause & Effect Language", description: "Explain relationships between events and outcomes." },
  literaryTerms: { title: "Literary Terms", description: "Understand the language of literary analysis." },
  reportedSpeech: { title: "Reported Speech", description: "Accurately report what others said or thought." },
  analysingAText: { title: "Analysing a Text", description: "Write a nuanced literary analysis." },
  culturalComparison: { title: "Cultural Comparison", description: "Compare cultural practices across different countries." },
  filmStudies: { title: "Film Studies", description: "Discuss cinematographic techniques and genres." },
  writingACriticalReview: { title: "Writing a Critical Review", description: "Produce a formal critical review of an artistic work." },
  psychologicalVocabulary: { title: "Psychological Vocabulary", description: "Discuss human behaviour, emotions and mental processes." },
  wishRegretStructures: { title: "Wish & Regret Structures", description: "Express wishes about the present and regrets about the past." },
  describingPersonality: { title: "Describing Personality", description: "Use precise vocabulary to discuss character traits." },
  humanBehaviourDiscussion: { title: "Human Behaviour Discussion", description: "Discuss and explain human actions and decisions." },
  formalEssayPsychology: { title: "Formal Essay – Psychology", description: "Write an analytical essay on a psychological topic." },
  emotionalIntelligence: { title: "Emotional Intelligence", description: "Understand concepts in modern psychology and wellness." },
  academicVocabularyInUse: { title: "Academic Vocabulary in Use", description: "Build the lexical range needed for university study." },
  complexSentenceStructures: { title: "Complex Sentence Structures", description: "Write with precision using advanced grammatical forms." },
  argumentativeEssay: { title: "Argumentative Essay", description: "Write a sophisticated, well-referenced academic argument." },
  seminarLectureSkills: { title: "Seminar & Lecture Skills", description: "Participate actively in academic discussions." },
  hedgingLanguage: { title: "Hedging Language", description: "Soften claims and express uncertainty academically." },
  citationReferencing: { title: "Citation & Referencing", description: "Use evidence correctly in academic writing." },
  businessFinance: { title: "Business & Finance", description: "Command the language of business and economics." },
  registerTone: { title: "Register & Tone", description: "Switch between formal and informal registers fluently." },
  negotiationLanguage: { title: "Negotiation Language", description: "Lead and respond in sophisticated business negotiations." },
  businessEmailReports: { title: "Business Email & Reports", description: "Write impeccable professional correspondence." },
  presentationsAdvanced: { title: "Presentations – Advanced", description: "Deliver a complex, structured business presentation." },
  leadershipManagement: { title: "Leadership & Management", description: "Discuss organizational structures and leadership styles." },
  philosophyVocabulary: { title: "Philosophy Vocabulary", description: "Engage with abstract concepts and philosophical terms." },
  advancedDiscourseMarkers: { title: "Advanced Discourse Markers", description: "Connect complex ideas seamlessly in writing and speech." },
  criticalThinkingEssay: { title: "Critical Thinking Essay", description: "Challenge and reconstruct arguments with precision." },
  philosophicalDebate: { title: "Philosophical Debate", description: "Engage in deep intellectual discussion." },
  logicalFallacies: { title: "Logical Fallacies", description: "Identify and name common reasoning errors." },
  researchSynthesis: { title: "Research Synthesis", description: "Synthesize multiple sources into a coherent argument." },
  mediaJournalism: { title: "Media & Journalism", description: "Analyse how language is used in media and press." },
  inversionEmphasis: { title: "Inversion & Emphasis", description: "Use grammatical inversion for dramatic or formal effect." },
  sociolinguistics: { title: "Sociolinguistics", description: "Understand dialect, sociolect, idiolect and language change." },
  advancedSpeakingOpinion: { title: "Advanced Speaking – Opinion", description: "Sustain long, complex monologues expressing nuanced views." },
  languagePower: { title: "Language & Power", description: "Write analytically about how language is used to influence." },
  interculturalCompetence: { title: "Intercultural Competence", description: "Navigate cultural differences in professional contexts." },
  idiomaticColloquialEnglish: { title: "Idiomatic & Colloquial English", description: "Use native-level idioms and vivid colloquial language." },
  rhetoricalDevices: { title: "Rhetorical Devices", description: "Write and speak with masterful rhetorical technique." },
  literaryAnalysis: { title: "Literary Analysis", description: "Produce a sophisticated, publishable literary critique." },
  translatingNuance: { title: "Translating Nuance", description: "Carry cultural and linguistic nuance across contexts." },
  nativeLevelDebate: { title: "Native-Level Debate", description: "Lead debates effortlessly at a fully native level." },
  voiceStyleInWriting: { title: "Voice & Style in Writing", description: "Develop a distinct, recognizable personal writing voice." },
  historicalPoliticalVocabulary: { title: "Historical & Political Vocabulary", description: "Discuss history, politics and civilisation with depth." },
  advancedInversionStructures: { title: "Advanced Inversion & Structures", description: "Command the most sophisticated grammatical structures." },
  researchPaperWriting: { title: "Research Paper Writing", description: "Write a polished academic research paper." },
  philosophicalPositionPaper: { title: "Philosophical Position Paper", description: "Argue a philosophical position with academic rigour." },
  culturalCommentary: { title: "Cultural Commentary", description: "Deliver complex cultural, political or social commentary." },
  satireIrony: { title: "Satire & Irony", description: "Understand and produce satirical and ironic text." },
  legalEnglish: { title: "Legal English", description: "Master formal language used in legal contexts." },
  medicalEnglish: { title: "Medical English", description: "Use precise medical terminology with confidence." },
  technicalScientificWriting: { title: "Technical & Scientific Writing", description: "Write flawless, unambiguous technical documentation." },
  financialEnglish: { title: "Financial English", description: "Navigate the vocabulary of banking and investment." },
  c2MockExamination: { title: "C2 Mock Examination", description: "Complete a full C2 proficiency exam simulation." },
  fullImmersionOpenDiscussion: { title: "Full Immersion – Open Discussion", description: "Sustain any topic at a completely native level indefinitely." },
};

export const LESSONS_PL: Record<string, LessonText> = {
  sayingHelloGoodbye: { title: "Powitania i pożegnania", description: "Naucz się najważniejszych codziennych zwrotów grzecznościowych." },
  introducingYourself: { title: "Przedstawianie się", description: "Podaj imię, wiek i miejsce pochodzenia." },
  countriesNationalities: { title: "Kraje i narodowości", description: "Nazywaj kraje i odpowiadające im przymiotniki narodowości." },
  numbers1100: { title: "Liczby 1–100", description: "Licz i używaj liczb w sytuacjach codziennych." },
  theVerbToBe: { title: "Czasownik „to be”", description: "Opanuj najważniejszy czasownik: am / is / are." },
  basicQuestionsAnswers: { title: "Podstawowe pytania i odpowiedzi", description: "Zadawaj i odpowiadaj na pytania who, what, where." },
  familyMembers: { title: "Członkowie rodziny", description: "Opisz swoje drzewo genealogiczne i relacje rodzinne." },
  describingPeople: { title: "Opisywanie ludzi", description: "Mów o wyglądzie i osobowości." },
  possessiveAdjectives: { title: "Zaimki dzierżawcze", description: "Poprawnie używaj my / your / his / her / our / their." },
  haveGotTalkingAboutFamily: { title: "Have got – o rodzinie", description: "Używaj „have got”, by mówić, co masz lub kogo znasz." },
  writingAboutYourFamily: { title: "Pisanie o rodzinie", description: "Napisz krótki akapit przedstawiający Twoją rodzinę." },
  familyInterview: { title: "Wywiad o rodzinie", description: "Zadawaj i odpowiadaj na pytania o życie rodzinne." },
  classroomObjects: { title: "Przedmioty w klasie", description: "Nazywaj rzeczy spotykane w środowisku nauki." },
  colorsShapes: { title: "Kolory i kształty", description: "Opisuj otoczenie kolorami i kształtami." },
  articlesAAnThe: { title: "Przedimki: a / an / the", description: "Wiedz, kiedy używać przedimków określonych i nieokreślonych." },
  thisThatTheseThose: { title: "This / That / These / Those", description: "Wskazuj rzeczy bliskie i odległe." },
  inTheClassroom: { title: "W klasie", description: "Opisuj otaczające Cię przedmioty pełnymi zdaniami." },
  spellingTheAlphabet: { title: "Literowanie i alfabet", description: "Literuj słowa głośno, używając angielskiego alfabetu." },
  daysMonthsSeasons: { title: "Dni, miesiące i pory roku", description: "Mów o kalendarzu: dni, miesiące i pory roku." },
  tellingTheTime: { title: "Określanie czasu", description: "Czytaj i mów, która jest godzina." },
  dailyRoutineVerbs: { title: "Czasowniki codziennej rutyny", description: "Opisz, co robisz od rana do wieczora." },
  presentSimpleDailyHabits: { title: "Present simple – codzienne nawyki", description: "Używaj present simple do opisu czynności rutynowych." },
  frequencyAdverbs: { title: "Przysłówki częstotliwości", description: "Wyrażaj, jak często coś się dzieje." },
  myTypicalDay: { title: "Mój typowy dzień", description: "Napisz lub opowiedz o swojej codziennej rutynie." },
  foodDrinkVocabulary: { title: "Słownictwo: jedzenie i napoje", description: "Nazywaj typowe potrawy i napoje." },
  orderingInARestaurant: { title: "Zamawianie w restauracji", description: "Prowadź realną rozmowę w kawiarni lub restauracji." },
  countableVsUncountable: { title: "Policzalne vs niepoliczalne", description: "Poprawnie używaj „some”, „any”, „much”, „many”." },
  expressingPreferences: { title: "Wyrażanie preferencji", description: "Mów, co lubisz, czego nie lubisz i co wolisz." },
  shoppingForFood: { title: "Zakupy spożywcze", description: "Kupuj jedzenie na targu lub w supermarkecie." },
  recipesInstructions: { title: "Przepisy i instrukcje", description: "Rozumiej słownictwo kulinarne i czytaj przepisy." },
  meansOfTransport: { title: "Środki transportu", description: "Nazywaj różne pojazdy i sposoby przemieszczania się." },
  buyingTickets: { title: "Kupowanie biletów", description: "Rezerwuj i kupuj bilety na przejazdy." },
  askingForDirections: { title: "Pytanie o drogę", description: "Odnajdź drogę w nowym mieście." },
  pastSimpleRegularVerbs: { title: "Past simple – czasowniki regularne", description: "Mów o czynnościach zakończonych w przeszłości." },
  pastSimpleIrregularVerbs: { title: "Past simple – czasowniki nieregularne", description: "Opanuj najpopularniejsze formy nieregularne." },
  describingAHoliday: { title: "Opisywanie wakacji", description: "Napisz lub opowiedz historię o minionej podróży." },
  roomsFurniture: { title: "Pokoje i meble", description: "Opisz układ i wyposażenie domu." },
  thereIsThereAre: { title: "There is / There are", description: "Opisuj, co znajduje się w danym miejscu." },
  prepositionsOfPlace: { title: "Przyimki miejsca", description: "Mów, gdzie znajdują się przedmioty." },
  describingYourHome: { title: "Opisywanie domu", description: "Opisz swój dom lub mieszkanie szczegółowo." },
  rentingAFlat: { title: "Wynajem mieszkania", description: "Rozumiej słownictwo związane z wynajmem nieruchomości." },
  makingComparisons: { title: "Tworzenie porównań", description: "Porównuj miejsca, przedmioty i ludzi." },
  partsOfTheBody: { title: "Części ciała", description: "Nazywaj i lokalizuj części ludzkiego ciała." },
  commonIllnessesSymptoms: { title: "Częste choroby i objawy", description: "Opisuj problemy zdrowotne i symptomy." },
  atTheDoctorS: { title: "U lekarza", description: "Komunikuj się z personelem medycznym." },
  shouldShouldnT: { title: "Should / Shouldn't", description: "Udzielaj porad zdrowotnych z użyciem czasowników modalnych." },
  healthyLifestyle: { title: "Zdrowy styl życia", description: "Pisz o nawykach prowadzących do zdrowego życia." },
  goingToThePharmacy: { title: "W aptece", description: "Kupuj leki i rozumiej zalecenia farmaceuty." },
  jobsResponsibilities: { title: "Zawody i obowiązki", description: "Mów o rodzajach pracy i obowiązkach zawodowych." },
  presentPerfectTense: { title: "Czas present perfect", description: "Łącz przeszłe doświadczenia z chwilą obecną." },
  cvCoverLetter: { title: "CV i list motywacyjny", description: "Pisz profesjonalne dokumenty aplikacyjne." },
  jobInterviewLanguage: { title: "Język rozmowy kwalifikacyjnej", description: "Mów pewnie podczas formalnej rozmowy o pracę." },
  workplaceVocabulary: { title: "Słownictwo biurowe", description: "Poruszaj się sprawnie w środowisku biurowym." },
  expressingFuturePlans: { title: "Wyrażanie planów na przyszłość", description: "Mów o zamiarach i planach na przyszłość." },
  digitalLifeVocabulary: { title: "Słownictwo cyfrowe", description: "Mów o technologii, aplikacjach i internecie." },
  thePassiveVoice: { title: "Strona bierna", description: "Przenoś nacisk z wykonawcy na czynność konstrukcjami biernymi." },
  discussingTechnology: { title: "Dyskusja o technologii", description: "Wyrażaj opinie o roli technologii w społeczeństwie." },
  readingOnlineArticles: { title: "Czytanie artykułów online", description: "Rozumiej złożone treści cyfrowe i media." },
  socialMediaCommunication: { title: "Media społecznościowe i komunikacja", description: "Pisz posty, komentarze i wiadomości w odpowiednim stylu." },
  technologyProblems: { title: "Problemy z technologią", description: "Opisuj awarie i rozwiązuj usterki sprzętowe." },
  natureLandscape: { title: "Natura i krajobraz", description: "Opisuj środowisko naturalne i cechy geograficzne." },
  environmentalProblems: { title: "Problemy ekologiczne", description: "Dyskutuj o zmianach klimatu i zagrożeniach środowiska." },
  modalVerbsForObligation: { title: "Modalne wyrażające obowiązek", description: "Wyrażaj obowiązek, pozwolenie i zakaz." },
  solutionsActions: { title: "Rozwiązania i działania", description: "Proponuj i debatuj o rozwiązaniach ekologicznych." },
  writingAReport: { title: "Pisanie raportu", description: "Buduj klarowną strukturę pisemnego raportu o problemie." },
  recyclingSustainability: { title: "Recykling i zrównoważony rozwój", description: "Rozumiej słownictwo związane z ekologicznym życiem." },
  hobbiesInterests: { title: "Hobby i zainteresowania", description: "Mów o zajęciach w czasie wolnym i pasjach." },
  gerundsInfinitives: { title: "Gerundy i bezokoliczniki", description: "Używaj form -ing i „to + verb” w odpowiednich kontekstach." },
  talkingAboutFilmsBooks: { title: "Filmy i książki", description: "Streszczaj fabuły i wyrażaj opinie o kulturze." },
  makingPlans: { title: "Planowanie spotkań", description: "Umawiaj się i organizuj wydarzenia w czasie przyszłym." },
  musicArt: { title: "Muzyka i sztuka", description: "Dyskutuj o dziełach, gatunkach i wykonaniach artystycznych." },
  reviewWriting: { title: "Pisanie recenzji", description: "Napisz porywającą recenzję filmu, książki lub miejsca." },
  socialIssuesVocabulary: { title: "Słownictwo: kwestie społeczne", description: "Dyskutuj o złożonych tematach współczesnego społeczeństwa." },
  conditionalSentencesAllTypes: { title: "Zdania warunkowe (wszystkie typy)", description: "Opanuj wszystkie tryby warunkowe – realne i hipotetyczne." },
  debatingArgumentation: { title: "Debata i argumentacja", description: "Wyrażaj, rozwijaj i broń złożone opinie." },
  opinionEssay: { title: "Esej opiniujący", description: "Napisz dobrze ułożony, perswazyjny esej opiniujący." },
  understandingStatistics: { title: "Rozumienie statystyk", description: "Czytaj i analizuj wykresy, dane i tendencje." },
  discourseConnectors: { title: "Konektory tekstu", description: "Popraw płynność wypowiedzi za pomocą wyrafinowanych spójników." },
  scientificVocabulary: { title: "Słownictwo naukowe", description: "Rozumiej język nauki i badań." },
  futureTensesAdvanced: { title: "Czasy przyszłe – zaawansowane", description: "Wyrażaj prawdopodobieństwo, plany i prognozy." },
  passiveVoiceAdvanced: { title: "Strona bierna – zaawansowana", description: "Używaj złożonych konstrukcji biernych w piśmie akademickim." },
  scienceReport: { title: "Raport naukowy", description: "Napisz formalny raport naukowy z wynikami badań." },
  discussingAiTheFuture: { title: "Dyskusja o AI i przyszłości", description: "Debatuj o wpływie technologii i sztucznej inteligencji." },
  causeEffectLanguage: { title: "Język przyczyny i skutku", description: "Wyjaśniaj relacje między zdarzeniami a ich konsekwencjami." },
  literaryTerms: { title: "Pojęcia literackie", description: "Rozumiej język analizy literackiej." },
  reportedSpeech: { title: "Mowa zależna", description: "Dokładnie relacjonuj słowa lub myśli innych." },
  analysingAText: { title: "Analiza tekstu", description: "Napisz wnikliwą analizę literacką." },
  culturalComparison: { title: "Porównanie kulturowe", description: "Porównuj zwyczaje kulturowe różnych krajów." },
  filmStudies: { title: "Filmoznawstwo", description: "Dyskutuj o technikach i gatunkach filmowych." },
  writingACriticalReview: { title: "Pisanie recenzji krytycznej", description: "Stwórz formalną recenzję krytyczną dzieła sztuki." },
  psychologicalVocabulary: { title: "Słownictwo psychologiczne", description: "Mów o ludzkich zachowaniach, emocjach i procesach mentalnych." },
  wishRegretStructures: { title: "Konstrukcje wish i regret", description: "Wyrażaj życzenia dotyczące teraźniejszości i żale o przeszłość." },
  describingPersonality: { title: "Opisywanie osobowości", description: "Używaj precyzyjnego słownictwa do opisu cech charakteru." },
  humanBehaviourDiscussion: { title: "Dyskusja o ludzkich zachowaniach", description: "Dyskutuj i wyjaśniaj ludzkie działania i decyzje." },
  formalEssayPsychology: { title: "Formalny esej – psychologia", description: "Napisz analityczny esej o tematyce psychologicznej." },
  emotionalIntelligence: { title: "Inteligencja emocjonalna", description: "Rozumiej koncepcje współczesnej psychologii i wellbeing." },
  academicVocabularyInUse: { title: "Słownictwo akademickie w praktyce", description: "Buduj zasób słownictwa potrzebny do studiów uniwersyteckich." },
  complexSentenceStructures: { title: "Złożone struktury zdaniowe", description: "Pisz precyzyjnie, używając zaawansowanych form gramatycznych." },
  argumentativeEssay: { title: "Esej argumentacyjny", description: "Napisz wyrafinowany, dobrze udokumentowany esej akademicki." },
  seminarLectureSkills: { title: "Umiejętności na seminariach i wykładach", description: "Aktywnie uczestnicz w dyskusjach akademickich." },
  hedgingLanguage: { title: "Język niepewności (hedging)", description: "Łagodź twierdzenia i wyrażaj niepewność akademicko." },
  citationReferencing: { title: "Cytowanie i bibliografia", description: "Poprawnie wykorzystuj źródła w pracach akademickich." },
  businessFinance: { title: "Biznes i finanse", description: "Opanuj język biznesu i ekonomii." },
  registerTone: { title: "Rejestr i ton", description: "Płynnie przełączaj się między rejestrem formalnym a nieformalnym." },
  negotiationLanguage: { title: "Język negocjacji", description: "Prowadź i odpowiadaj w wyrafinowanych negocjacjach biznesowych." },
  businessEmailReports: { title: "E-maile i raporty biznesowe", description: "Pisz nienaganną korespondencję profesjonalną." },
  presentationsAdvanced: { title: "Prezentacje – zaawansowane", description: "Wygłoś złożoną, ustrukturyzowaną prezentację biznesową." },
  leadershipManagement: { title: "Przywództwo i zarządzanie", description: "Dyskutuj o strukturach organizacyjnych i stylach przywództwa." },
  philosophyVocabulary: { title: "Słownictwo filozoficzne", description: "Pracuj z abstrakcyjnymi pojęciami i terminami filozoficznymi." },
  advancedDiscourseMarkers: { title: "Zaawansowane spójniki dyskursu", description: "Łącz złożone idee w piśmie i mowie bez szwów." },
  criticalThinkingEssay: { title: "Esej krytycznego myślenia", description: "Z precyzją obalaj i przebudowuj argumenty." },
  philosophicalDebate: { title: "Debata filozoficzna", description: "Bierz udział w głębokiej dyskusji intelektualnej." },
  logicalFallacies: { title: "Błędy logiczne", description: "Identyfikuj i nazywaj typowe błędy w rozumowaniu." },
  researchSynthesis: { title: "Synteza badań", description: "Łącz wiele źródeł w spójny argument." },
  mediaJournalism: { title: "Media i dziennikarstwo", description: "Analizuj, jak język jest używany w mediach i prasie." },
  inversionEmphasis: { title: "Inwersja i emfaza", description: "Stosuj inwersję gramatyczną w celach dramatycznych lub formalnych." },
  sociolinguistics: { title: "Socjolingwistyka", description: "Rozumiej dialekt, socjolekt, idiolekt i zmiany językowe." },
  advancedSpeakingOpinion: { title: "Zaawansowana wypowiedź – opinia", description: "Prowadź długie, złożone monologi z subtelnymi opiniami." },
  languagePower: { title: "Język i władza", description: "Pisz analitycznie o tym, jak język wpływa na ludzi." },
  interculturalCompetence: { title: "Kompetencje międzykulturowe", description: "Radź sobie z różnicami kulturowymi w środowisku zawodowym." },
  idiomaticColloquialEnglish: { title: "Angielski idiomatyczny i potoczny", description: "Używaj idiomów i barwnego języka mówionego na poziomie native." },
  rhetoricalDevices: { title: "Środki retoryczne", description: "Pisz i mów z mistrzowskim opanowaniem retoryki." },
  literaryAnalysis: { title: "Analiza literacka", description: "Stwórz wyrafinowaną krytykę literacką gotową do publikacji." },
  translatingNuance: { title: "Tłumaczenie niuansów", description: "Przenoś niuanse kulturowe i językowe między kontekstami." },
  nativeLevelDebate: { title: "Debata na poziomie native", description: "Prowadź debaty bez wysiłku na pełnym poziomie native." },
  voiceStyleInWriting: { title: "Głos i styl w piśmie", description: "Wypracuj wyraźny, rozpoznawalny styl pisarski." },
  historicalPoliticalVocabulary: { title: "Słownictwo historyczno-polityczne", description: "Mów o historii, polityce i cywilizacji z głębią." },
  advancedInversionStructures: { title: "Zaawansowane inwersje i struktury", description: "Opanuj najbardziej wyrafinowane struktury gramatyczne." },
  researchPaperWriting: { title: "Pisanie pracy badawczej", description: "Napisz dopracowaną akademicką pracę badawczą." },
  philosophicalPositionPaper: { title: "Praca prezentująca stanowisko filozoficzne", description: "Argumentuj stanowisko filozoficzne z akademicką rygorystycznością." },
  culturalCommentary: { title: "Komentarz kulturowy", description: "Wygłaszaj złożone komentarze kulturowe, polityczne lub społeczne." },
  satireIrony: { title: "Satyra i ironia", description: "Rozumiej i twórz teksty satyryczne i ironiczne." },
  legalEnglish: { title: "Angielski prawniczy", description: "Opanuj formalny język używany w kontekstach prawnych." },
  medicalEnglish: { title: "Angielski medyczny", description: "Posługuj się precyzyjną terminologią medyczną z pewnością." },
  technicalScientificWriting: { title: "Pisanie techniczne i naukowe", description: "Pisz nienaganną, jednoznaczną dokumentację techniczną." },
  financialEnglish: { title: "Angielski finansowy", description: "Poruszaj się sprawnie w słownictwie bankowym i inwestycyjnym." },
  c2MockExamination: { title: "Próbny egzamin C2", description: "Przejdź pełną symulację egzaminu biegłości C2." },
  fullImmersionOpenDiscussion: { title: "Pełne zanurzenie – otwarta dyskusja", description: "Prowadź dowolny temat na poziomie native bez ograniczeń." },
};

export const LESSONS_ES: Record<string, LessonText> = {
  sayingHelloGoodbye: { title: "Saludar y despedirse", description: "Aprende los saludos diarios más esenciales." },
  introducingYourself: { title: "Presentarse", description: "Di tu nombre, edad y de dónde eres." },
  countriesNationalities: { title: "Países y nacionalidades", description: "Nombra países y los adjetivos de nacionalidad correspondientes." },
  numbers1100: { title: "Números 1–100", description: "Cuenta y usa números en contextos cotidianos." },
  theVerbToBe: { title: "El verbo «to be»", description: "Domina el verbo más fundamental: am / is / are." },
  basicQuestionsAnswers: { title: "Preguntas y respuestas básicas", description: "Haz y responde preguntas con who, what, where." },
  familyMembers: { title: "Miembros de la familia", description: "Describe tu árbol familiar y las relaciones." },
  describingPeople: { title: "Describir personas", description: "Habla del aspecto físico y la personalidad." },
  possessiveAdjectives: { title: "Adjetivos posesivos", description: "Usa my / your / his / her / our / their correctamente." },
  haveGotTalkingAboutFamily: { title: "Have got – hablar de la familia", description: "Usa «have got» para describir lo que tienes o a quién conoces." },
  writingAboutYourFamily: { title: "Escribir sobre tu familia", description: "Escribe un breve párrafo presentando a tu familia." },
  familyInterview: { title: "Entrevista familiar", description: "Haz y responde preguntas sobre la vida familiar." },
  classroomObjects: { title: "Objetos del aula", description: "Nombra elementos típicos de un entorno de aprendizaje." },
  colorsShapes: { title: "Colores y formas", description: "Describe tu entorno con colores y formas." },
  articlesAAnThe: { title: "Artículos: a / an / the", description: "Sabe cuándo usar artículos definidos e indefinidos." },
  thisThatTheseThose: { title: "This / That / These / Those", description: "Señala objetos cercanos y lejanos." },
  inTheClassroom: { title: "En el aula", description: "Describe los objetos a tu alrededor con frases completas." },
  spellingTheAlphabet: { title: "Deletreo y alfabeto", description: "Deletrea palabras en voz alta usando el alfabeto inglés." },
  daysMonthsSeasons: { title: "Días, meses y estaciones", description: "Habla del calendario: días, meses y estaciones." },
  tellingTheTime: { title: "Decir la hora", description: "Lee y di qué hora es." },
  dailyRoutineVerbs: { title: "Verbos de rutina diaria", description: "Describe lo que haces de la mañana a la noche." },
  presentSimpleDailyHabits: { title: "Present simple – hábitos diarios", description: "Usa el present simple para hablar de acciones habituales." },
  frequencyAdverbs: { title: "Adverbios de frecuencia", description: "Expresa con qué frecuencia ocurren las cosas." },
  myTypicalDay: { title: "Mi día típico", description: "Escribe o cuenta tu rutina diaria." },
  foodDrinkVocabulary: { title: "Vocabulario de comida y bebida", description: "Nombra alimentos y bebidas comunes." },
  orderingInARestaurant: { title: "Pedir en un restaurante", description: "Mantén una conversación real en un café o restaurante." },
  countableVsUncountable: { title: "Contable vs incontable", description: "Usa «some», «any», «much», «many» correctamente." },
  expressingPreferences: { title: "Expresar preferencias", description: "Di lo que te gusta, lo que no y lo que prefieres." },
  shoppingForFood: { title: "Comprar comida", description: "Compra alimentos en un mercado o supermercado." },
  recipesInstructions: { title: "Recetas e instrucciones", description: "Comprende vocabulario de cocina y sigue una receta." },
  meansOfTransport: { title: "Medios de transporte", description: "Nombra distintos vehículos y formas de desplazarse." },
  buyingTickets: { title: "Comprar billetes", description: "Reserva y compra billetes de transporte." },
  askingForDirections: { title: "Pedir indicaciones", description: "Encuentra tu camino en una ciudad nueva." },
  pastSimpleRegularVerbs: { title: "Past simple – verbos regulares", description: "Habla de acciones terminadas en el pasado." },
  pastSimpleIrregularVerbs: { title: "Past simple – verbos irregulares", description: "Domina las formas irregulares más comunes." },
  describingAHoliday: { title: "Describir unas vacaciones", description: "Escribe o cuenta una historia sobre un viaje pasado." },
  roomsFurniture: { title: "Habitaciones y muebles", description: "Describe la distribución y el contenido de una vivienda." },
  thereIsThereAre: { title: "There is / There are", description: "Describe lo que hay en un lugar." },
  prepositionsOfPlace: { title: "Preposiciones de lugar", description: "Indica dónde están situadas las cosas." },
  describingYourHome: { title: "Describir tu casa", description: "Describe tu casa o piso con detalle." },
  rentingAFlat: { title: "Alquilar un piso", description: "Comprende el lenguaje para buscar y alquilar vivienda." },
  makingComparisons: { title: "Hacer comparaciones", description: "Compara lugares, objetos y personas." },
  partsOfTheBody: { title: "Partes del cuerpo", description: "Nombra y localiza las partes del cuerpo humano." },
  commonIllnessesSymptoms: { title: "Enfermedades y síntomas comunes", description: "Describe problemas de salud y síntomas." },
  atTheDoctorS: { title: "En el médico", description: "Comunícate con un profesional sanitario." },
  shouldShouldnT: { title: "Should / Shouldn't", description: "Da consejos de salud usando verbos modales." },
  healthyLifestyle: { title: "Estilo de vida saludable", description: "Escribe sobre hábitos para una vida sana." },
  goingToThePharmacy: { title: "Ir a la farmacia", description: "Compra medicamentos y entiende las instrucciones." },
  jobsResponsibilities: { title: "Trabajos y responsabilidades", description: "Habla de tipos de trabajo y deberes profesionales." },
  presentPerfectTense: { title: "Tiempo present perfect", description: "Conecta experiencias pasadas con el momento presente." },
  cvCoverLetter: { title: "CV y carta de presentación", description: "Escribe documentos de candidatura profesionales." },
  jobInterviewLanguage: { title: "Lenguaje para entrevistas", description: "Habla con seguridad en una entrevista de trabajo formal." },
  workplaceVocabulary: { title: "Vocabulario laboral", description: "Desenvuélvete en la oficina y entornos profesionales." },
  expressingFuturePlans: { title: "Expresar planes futuros", description: "Habla de intenciones y planes a futuro." },
  digitalLifeVocabulary: { title: "Vocabulario de vida digital", description: "Habla de tecnología, aplicaciones e internet." },
  thePassiveVoice: { title: "La voz pasiva", description: "Cambia el foco del actor a la acción usando construcciones pasivas." },
  discussingTechnology: { title: "Debatir sobre tecnología", description: "Comparte opiniones sobre el papel de la tecnología en la sociedad." },
  readingOnlineArticles: { title: "Leer artículos en línea", description: "Comprende contenidos digitales y medios complejos." },
  socialMediaCommunication: { title: "Redes sociales y comunicación", description: "Escribe publicaciones, comentarios y mensajes adecuados." },
  technologyProblems: { title: "Problemas tecnológicos", description: "Describe y soluciona incidencias tecnológicas." },
  natureLandscape: { title: "Naturaleza y paisaje", description: "Describe entornos naturales y rasgos geográficos." },
  environmentalProblems: { title: "Problemas medioambientales", description: "Debate sobre el cambio climático y problemas ecológicos." },
  modalVerbsForObligation: { title: "Modales de obligación", description: "Expresa deber, permiso y prohibición." },
  solutionsActions: { title: "Soluciones y acciones", description: "Propón y debate soluciones medioambientales." },
  writingAReport: { title: "Escribir un informe", description: "Estructura un informe escrito claro sobre un tema." },
  recyclingSustainability: { title: "Reciclaje y sostenibilidad", description: "Comprende el lenguaje sobre la vida sostenible." },
  hobbiesInterests: { title: "Hobbies e intereses", description: "Habla de actividades de tiempo libre y aficiones." },
  gerundsInfinitives: { title: "Gerundios e infinitivos", description: "Usa formas en -ing y «to + verb» en los contextos correctos." },
  talkingAboutFilmsBooks: { title: "Hablar de cine y libros", description: "Resume tramas y expresa opiniones sobre cultura." },
  makingPlans: { title: "Hacer planes", description: "Organiza eventos usando formas de futuro." },
  musicArt: { title: "Música y arte", description: "Comenta obras, géneros e interpretaciones artísticas." },
  reviewWriting: { title: "Escribir reseñas", description: "Escribe una reseña atractiva de una película, libro o lugar." },
  socialIssuesVocabulary: { title: "Vocabulario de temas sociales", description: "Debate temas complejos que afectan a la sociedad moderna." },
  conditionalSentencesAllTypes: { title: "Condicionales (todos los tipos)", description: "Domina todos los condicionales para hechos reales e hipotéticos." },
  debatingArgumentation: { title: "Debate y argumentación", description: "Expresa, desarrolla y defiende opiniones complejas." },
  opinionEssay: { title: "Ensayo de opinión", description: "Escribe un ensayo de opinión bien estructurado y persuasivo." },
  understandingStatistics: { title: "Comprender estadísticas", description: "Lee y comenta gráficos, datos y tendencias." },
  discourseConnectors: { title: "Conectores del discurso", description: "Mejora la fluidez con conectores sofisticados." },
  scientificVocabulary: { title: "Vocabulario científico", description: "Comprende el lenguaje usado en ciencia e investigación." },
  futureTensesAdvanced: { title: "Tiempos futuros – avanzado", description: "Expresa probabilidad, planes y predicciones futuras." },
  passiveVoiceAdvanced: { title: "Voz pasiva – avanzada", description: "Usa estructuras pasivas complejas en escritura académica." },
  scienceReport: { title: "Informe científico", description: "Escribe un informe científico formal con resultados." },
  discussingAiTheFuture: { title: "Debate sobre IA y el futuro", description: "Debate el impacto de la tecnología y la inteligencia artificial." },
  causeEffectLanguage: { title: "Lenguaje de causa y efecto", description: "Explica relaciones entre eventos y resultados." },
  literaryTerms: { title: "Términos literarios", description: "Comprende el lenguaje del análisis literario." },
  reportedSpeech: { title: "Estilo indirecto", description: "Reporta con precisión lo que otros han dicho o pensado." },
  analysingAText: { title: "Analizar un texto", description: "Escribe un análisis literario matizado." },
  culturalComparison: { title: "Comparación cultural", description: "Compara prácticas culturales de distintos países." },
  filmStudies: { title: "Estudios cinematográficos", description: "Comenta técnicas y géneros cinematográficos." },
  writingACriticalReview: { title: "Escribir reseña crítica", description: "Produce una reseña crítica formal de una obra artística." },
  psychologicalVocabulary: { title: "Vocabulario psicológico", description: "Habla de la conducta humana, las emociones y los procesos mentales." },
  wishRegretStructures: { title: "Estructuras wish y regret", description: "Expresa deseos sobre el presente y arrepentimientos sobre el pasado." },
  describingPersonality: { title: "Describir la personalidad", description: "Usa vocabulario preciso para describir rasgos de carácter." },
  humanBehaviourDiscussion: { title: "Debate sobre la conducta humana", description: "Debate y explica acciones y decisiones humanas." },
  formalEssayPsychology: { title: "Ensayo formal – psicología", description: "Escribe un ensayo analítico sobre un tema psicológico." },
  emotionalIntelligence: { title: "Inteligencia emocional", description: "Comprende conceptos de psicología y bienestar moderno." },
  academicVocabularyInUse: { title: "Vocabulario académico en uso", description: "Construye el vocabulario necesario para los estudios universitarios." },
  complexSentenceStructures: { title: "Estructuras oracionales complejas", description: "Escribe con precisión usando formas gramaticales avanzadas." },
  argumentativeEssay: { title: "Ensayo argumentativo", description: "Escribe un argumento académico sofisticado y bien referenciado." },
  seminarLectureSkills: { title: "Habilidades de seminario y clase", description: "Participa activamente en discusiones académicas." },
  hedgingLanguage: { title: "Lenguaje de matización", description: "Suaviza afirmaciones y expresa incertidumbre académicamente." },
  citationReferencing: { title: "Citas y referencias", description: "Usa fuentes correctamente en escritura académica." },
  businessFinance: { title: "Negocios y finanzas", description: "Domina el lenguaje de los negocios y la economía." },
  registerTone: { title: "Registro y tono", description: "Cambia entre registro formal e informal con fluidez." },
  negotiationLanguage: { title: "Lenguaje de negociación", description: "Lidera y responde en negociaciones empresariales sofisticadas." },
  businessEmailReports: { title: "Correos e informes empresariales", description: "Escribe correspondencia profesional impecable." },
  presentationsAdvanced: { title: "Presentaciones – avanzado", description: "Da una presentación empresarial compleja y bien estructurada." },
  leadershipManagement: { title: "Liderazgo y gestión", description: "Comenta estructuras organizativas y estilos de liderazgo." },
  philosophyVocabulary: { title: "Vocabulario filosófico", description: "Trabaja con conceptos abstractos y términos filosóficos." },
  advancedDiscourseMarkers: { title: "Marcadores de discurso avanzados", description: "Conecta ideas complejas con fluidez en escritura y oralidad." },
  criticalThinkingEssay: { title: "Ensayo de pensamiento crítico", description: "Cuestiona y reconstruye argumentos con precisión." },
  philosophicalDebate: { title: "Debate filosófico", description: "Participa en discusiones intelectuales profundas." },
  logicalFallacies: { title: "Falacias lógicas", description: "Identifica y nombra errores comunes de razonamiento." },
  researchSynthesis: { title: "Síntesis de investigación", description: "Sintetiza varias fuentes en un argumento coherente." },
  mediaJournalism: { title: "Medios y periodismo", description: "Analiza cómo se usa el lenguaje en medios y prensa." },
  inversionEmphasis: { title: "Inversión y énfasis", description: "Usa la inversión gramatical con efecto dramático o formal." },
  sociolinguistics: { title: "Sociolingüística", description: "Comprende dialecto, sociolecto, idiolecto y cambio lingüístico." },
  advancedSpeakingOpinion: { title: "Habla avanzada – opinión", description: "Sostén monólogos largos y complejos con opiniones matizadas." },
  languagePower: { title: "Lenguaje y poder", description: "Escribe analíticamente sobre cómo el lenguaje se usa para influir." },
  interculturalCompetence: { title: "Competencia intercultural", description: "Maneja diferencias culturales en contextos profesionales." },
  idiomaticColloquialEnglish: { title: "Inglés idiomático y coloquial", description: "Usa modismos y lenguaje coloquial vívido a nivel nativo." },
  rhetoricalDevices: { title: "Recursos retóricos", description: "Escribe y habla con técnica retórica magistral." },
  literaryAnalysis: { title: "Análisis literario", description: "Produce una crítica literaria sofisticada y publicable." },
  translatingNuance: { title: "Traducir matices", description: "Transmite matices culturales y lingüísticos entre contextos." },
  nativeLevelDebate: { title: "Debate a nivel nativo", description: "Lidera debates con soltura a nivel completamente nativo." },
  voiceStyleInWriting: { title: "Voz y estilo en la escritura", description: "Desarrolla una voz escrita personal y reconocible." },
  historicalPoliticalVocabulary: { title: "Vocabulario histórico y político", description: "Comenta historia, política y civilización con profundidad." },
  advancedInversionStructures: { title: "Inversión y estructuras avanzadas", description: "Domina las estructuras gramaticales más sofisticadas." },
  researchPaperWriting: { title: "Escribir un trabajo de investigación", description: "Escribe un trabajo académico de investigación pulido." },
  philosophicalPositionPaper: { title: "Ensayo de posición filosófica", description: "Argumenta una posición filosófica con rigor académico." },
  culturalCommentary: { title: "Comentario cultural", description: "Ofrece comentarios culturales, políticos o sociales complejos." },
  satireIrony: { title: "Sátira e ironía", description: "Comprende y produce textos satíricos e irónicos." },
  legalEnglish: { title: "Inglés jurídico", description: "Domina el lenguaje formal usado en contextos legales." },
  medicalEnglish: { title: "Inglés médico", description: "Usa terminología médica precisa con confianza." },
  technicalScientificWriting: { title: "Escritura técnica y científica", description: "Escribe documentación técnica impecable y sin ambigüedades." },
  financialEnglish: { title: "Inglés financiero", description: "Maneja el vocabulario de banca e inversión." },
  c2MockExamination: { title: "Examen simulado C2", description: "Completa una simulación de examen de competencia C2." },
  fullImmersionOpenDiscussion: { title: "Inmersión total – discusión abierta", description: "Sostén cualquier tema a nivel completamente nativo, sin límites." },
};

const ALL: Record<string, Record<string, LessonText>> = {
  en: LESSONS_EN,
  pl: LESSONS_PL,
  es: LESSONS_ES,
};

/** Lookup `{title, description}` for a slug. Falls back through:
 *   1. requested locale → 2. English → 3. undefined (caller supplies fallback). */
export function lookupLesson(
  slug: string,
  locale: string,
): LessonText | undefined {
  const lang = (locale || "en").split("-")[0].toLowerCase();
  return ALL[lang]?.[slug] ?? ALL.en?.[slug];
}
